model: src.models.birnn_model.BiRNNModel
model_params:
  use_char: False
  dropout_keep_prob: 0.5
  embedding.word_dim: 100
  embedding.char_dim: 25
  encoder.class: BiLSTM
  encoder.params:
    rnn_cell:
      cell_class: LSTMCell
      num_units: 100
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
  optimizer.name: adam
  optimizer.lr_decay_rate: 0.9
  optimizer.learning_rate: 0.001
  optimizer.clip_gradients: 5
  count_vocab_source: 0
  count_vocab_char: 0
  count_vocab_target: 0
  keep_checkpoint_max: 5
